name: Publish Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.14.6
      uses: actions/setup-python@v5
      with:
        python-version: '3.14.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas xlsxwriter

    - name: Build with PyInstaller
      run: pyinstaller --onefile --name word-metadata-extractor --hidden-import=xlsxwriter word-metadata-extractor.py

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}